- name : demo on play level variables
  hosts : all
  vars :
    input : play level
  tasks :
    - name : print url
      ansible.builtin.debug :
        msg : url - {{input}}

- name : demo on task level variables
  hosts : all
  tasks :
    - name : print url
      vars :
        input : task level
      ansible.builtin.debug :
        msg : "{{input}}"

